In [2]:
import numpy as np
from copy import deepcopy
import queue
import time
from collections import deque

In [14]:
# A class to define 8 puzzle board with properties and moves
class Board():
    def __init__(self,initial):
        self.initial= np.array(initial)
        self.board = np.reshape (initial,(-1,3))
        print("node created")
        self.parent = None
        self.move = None
        self.depth= 0
        
    
    def display(self):
        print(self.board)
    
    # Find the index of 0
    def find_zero(self):
        start=np.where(self.board==0)
        return (int(start[0]), int(start[1]))
    
    # compute valid moves for each state
    def get_valid_moves(self):
        start = self.find_zero()
        
        #priority order for valid moves 
        valid_moves = ['up', 'down', 'left', 'right']
       
        # IF the zero element is in top row
        if((start[0]-1)< 0): 
            valid_moves.remove('up')
            
        # IF the zero element is in bottom row
        if((start[0]+1)> 2):
            valid_moves.remove('down')
        
        # IF the zero element is in first column
        if((start[1]-1)< 0): 
            valid_moves.remove('left')    
        
        # IF the zero element is in last column
        if((start[1]+1)> 2): 
            valid_moves.remove('right')    
        
        return valid_moves
        
    # Function to generate each child    
    def children(self):
        s = self.find_zero()
        children = []
        valid_moves = self.get_valid_moves()
        for move in valid_moves:
           
        #New object for Children
            child = deepcopy(self) 
            if move == 'up':
                x = child.board.item(s[0],s[1])
                child.board.itemset(((s[0]),s[1]), child.board.item(s[0]-1,s[1]))
                child.board.itemset((s[0]-1,s[1]), x)
            
            if move == 'down':
                x = child.board.item(s[0],s[1])
                child.board.itemset(((s[0]),s[1]), child.board.item(s[0]+1,s[1]))
                child.board.itemset((s[0]+1,s[1]), x)
            
            if move == 'left':
                x = child.board.item(s[0],s[1])
                child.board.itemset(((s[0]),s[1]), child.board.item(s[0],s[1]-1))
                child.board.itemset((s[0],s[1]-1), x)
            
            if move == 'right':
                x = child.board.item(s[0],s[1])
                child.board.itemset(((s[0]),s[1]), child.board.item(s[0],s[1]+1))
                child.board.itemset((s[0],s[1]+1), x)
            
            child.move = move
            children.append(child)
        return children
    
    def goal_check(self):
        goal = np.array([0,1,2,3,4,5,6,7,8])
        goal = np.reshape(goal, (-1,3))
        return np.array_equal(goal,self.board)

In [15]:
def BFS(board):
    

    startTime = time.time()
    frontier = queue.Queue()
    frontier.put(board)
    print(board.board)
    explored = set([])
    result = False

    while not frontier.empty():
        state = frontier.get()
        if state.goal_check():
            result = True
        
            print("goal")
            break
        explored.add(state)
    
    
        #children function returns list of set {board (child[0]), move(child[1])}
        for child in state.children():
            child.depth= state.depth +1
            child.parent= state
       
        # check if the child is already analyzed
        #for each in frontier:
            x = False
            for each in explored:
                x=np.array_equal(child.board,each.board)
                
                if x == True : break
        # If the item is not on the explored set, then add it
            if x == False:
                frontier.put(child)

    elapsed_time = time.time() - startTime
    path = deque()
# Print the result
    if result == True:
        print("Depth of the result: ", state.depth )
        while state.parent != None:
            path.appendleft(state.move)
            state = state.parent
        
        print(path)
        print("Total expanded node :  " ,len(explored))
        print("Total time taken: ", elapsed_time)
    


In [18]:
def DFS(board):
    

    startTime = time.time()
    frontier = []
    frontier.append(board)
    print(board.board)
    explored = set([])
    result = False

    while frontier:
        state = frontier.pop()
        if state.goal_check():
            result = True
        
            print("goal")
            break
        explored.add(state)
    
    
        #children function returns list of set {board (child[0]), move(child[1])}
        for child in state.children():
            
            child.depth= state.depth + 1
            child.parent= state
          
            y = False
            for each in frontier:
                y=np.array_equal(child.board,each.board)
                print("frontier", x)
                if y == True: break
            if y == True: break
        # check if the child is already analyzed
      
            x = False
            for each in explored:
                x=np.array_equal(child.board,each.board)
                print("explored", x)
                if x == True: break
        # If the item is not on the explored set, then add it
            if x == False:
                #print("child", child.move)
                frontier.append(child)

    elapsed_time = time.time() - startTime
    path = deque()
    
# Print the result
    if result == True:
        print("Depth of the result: ", state.depth )
        while state.parent != None:
            path.appendleft(state.move)
            state = state.parent
        
        print(path)
        print("Total expanded node :  " ,len(explored))
        print("Total time taken: ", elapsed_time)

In [19]:
board= Board([1,2,0,3,4,5,6,7,8])
DFS(board)

node created
[[1 2 0]
 [3 4 5]
 [6 7 8]]
explored False
frontier False
explored False
frontier False
explored False
explored False
frontier False
frontier False
explored False
explored True
frontier True
frontier True
explored False
explored False
goal
Depth of the result:  2
deque(['left', 'left'])
Total expanded node :   2
Total time taken:  0.0020024776458740234
